export default {
  page: {
    backgroundColor: 'white',
  },
  pageContainer: {
    flexGrow: 1,
    flexShrink: 0,
    flexBasis: 0,
    flexDirection: 'row',
    flexWrap: 'wrap',
    height: '100%',
  },
  hero: {
    width: '100%',
    paddingHorizontal: 10,
  },
  leftContainer: {
    width: '25%',
    maxWidth: '25%',
    paddingTop: 10,
    paddingLeft: 30,
    paddingRight: 20,
    height: '75%',
    flex: 1,
    flexGrow: 1,
    flexShrink: 0,
  },
  rightContainer: {
    width: '72%',
    maxWidth: '75%',
    height: '85%',
    borderLeft: 2,
    borderLeftColor: '#e5eced',
    paddingTop: 10,
    paddingHorizontal: 10,
    flex: 1,
    flexGrow: 1,
    flexShrink: 0,
  },
  title: {
    color: '#006CB4',
    fontSize: '14',
    marginBottom: 5,
    textAlign: 'left',
    wordWrap: 'normal',
  },
  results: {
    flex: 1,
    flexGrow: 1,
    flexShrink: 0,
    flexBasis: 0,
    flexDirection: 'column',
  },
  row: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 0,
    flexDirection: 'row',
  },
  rowSpacer: {
    marginVertical: 5,
  },
  ctaSection: {
    border: 1,
    padding: 10,
    borderTopLeftRadius: 5,
    borderTopRightRadius: 5,
    borderBottomRightRadius: 5,
    borderBottomLeftRadius: 5,
    borderColor: '#007f9a',
    alignItems: 'center',
    height: 55,
  },
  text: {
    fontSize: '9',
    color: '#58595b',
  },
  textDisclaimer: {
    fontSize: '8',
    color: '#58595b',
  },
  textList: {
    paddingRight: 8,
    paddingLeft: 8,
  },
  textBold: {
    fontSize: '10',
    color: '#58595b',
    fontWeight: 'bold',
  },
  itemText: {
    textAlign: 'left',
    paddingTop: 5,
    paddingHorizontal: 10,
    color: '#006CB4',
    fontWeight: 'bold',
    fontSize: 12,
    marginRight: 100,
  },
  can: {
    width: '100%',
    height: 'auto',
  },
  arrow: {
    width: 5,
    height: 5,
    alignItems: 'left',
    marginBottom: 7,
  },
  generalScore: {
    border: 2,
    padding: 10,
  },
};
